version: "3"
services:
  api:
    image: rtmp-streamer
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  # web-cli:
  #   image: sample-express-app
  #   networks:
  #     - backend
  #   command: sh

networks:
  backend:
    driver: bridge
