version: "3"
services:
  api:
    image: rtmp-streamer
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - backend
    expose:
      - 3000
    ports:
      - "3000:3000"

  # web-cli:
  #   image: sample-express-app
  #   networks:
  #     - backend
  #   command: sh

networks:
  backend:
    driver: bridge
